# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/claramuller/workspace/offsprintsubject/algolia-suggest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/claramuller/workspace/offsprintsubject/algolia-suggest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/claramuller/workspace/offsprintsubject/algolia-suggest/CMakeFiles /Users/claramuller/workspace/offsprintsubject/algolia-suggest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/claramuller/workspace/offsprintsubject/algolia-suggest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named algolia-suggest

# Build rule for target.
algolia-suggest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algolia-suggest
.PHONY : algolia-suggest

# fast build rule for target.
algolia-suggest/fast:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/build
.PHONY : algolia-suggest/fast

#=============================================================================
# Target rules for targets named SearchStaticLib

# Build rule for target.
SearchStaticLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SearchStaticLib
.PHONY : SearchStaticLib

# fast build rule for target.
SearchStaticLib/fast:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/build
.PHONY : SearchStaticLib/fast

#=============================================================================
# Target rules for targets named algolia-suggest_autogen

# Build rule for target.
algolia-suggest_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algolia-suggest_autogen
.PHONY : algolia-suggest_autogen

# fast build rule for target.
algolia-suggest_autogen/fast:
	$(MAKE) -f CMakeFiles/algolia-suggest_autogen.dir/build.make CMakeFiles/algolia-suggest_autogen.dir/build
.PHONY : algolia-suggest_autogen/fast

#=============================================================================
# Target rules for targets named SearchStaticLib_autogen

# Build rule for target.
SearchStaticLib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SearchStaticLib_autogen
.PHONY : SearchStaticLib_autogen

# fast build rule for target.
SearchStaticLib_autogen/fast:
	$(MAKE) -f CMakeFiles/SearchStaticLib_autogen.dir/build.make CMakeFiles/SearchStaticLib_autogen.dir/build
.PHONY : SearchStaticLib_autogen/fast

SearchStaticLib_autogen/mocs_compilation.o: SearchStaticLib_autogen/mocs_compilation.cpp.o

.PHONY : SearchStaticLib_autogen/mocs_compilation.o

# target to build an object file
SearchStaticLib_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/SearchStaticLib_autogen/mocs_compilation.cpp.o
.PHONY : SearchStaticLib_autogen/mocs_compilation.cpp.o

SearchStaticLib_autogen/mocs_compilation.i: SearchStaticLib_autogen/mocs_compilation.cpp.i

.PHONY : SearchStaticLib_autogen/mocs_compilation.i

# target to preprocess a source file
SearchStaticLib_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/SearchStaticLib_autogen/mocs_compilation.cpp.i
.PHONY : SearchStaticLib_autogen/mocs_compilation.cpp.i

SearchStaticLib_autogen/mocs_compilation.s: SearchStaticLib_autogen/mocs_compilation.cpp.s

.PHONY : SearchStaticLib_autogen/mocs_compilation.s

# target to generate assembly for a file
SearchStaticLib_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/SearchStaticLib_autogen/mocs_compilation.cpp.s
.PHONY : SearchStaticLib_autogen/mocs_compilation.cpp.s

algolia-suggest_autogen/mocs_compilation.o: algolia-suggest_autogen/mocs_compilation.cpp.o

.PHONY : algolia-suggest_autogen/mocs_compilation.o

# target to build an object file
algolia-suggest_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/algolia-suggest_autogen/mocs_compilation.cpp.o
.PHONY : algolia-suggest_autogen/mocs_compilation.cpp.o

algolia-suggest_autogen/mocs_compilation.i: algolia-suggest_autogen/mocs_compilation.cpp.i

.PHONY : algolia-suggest_autogen/mocs_compilation.i

# target to preprocess a source file
algolia-suggest_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/algolia-suggest_autogen/mocs_compilation.cpp.i
.PHONY : algolia-suggest_autogen/mocs_compilation.cpp.i

algolia-suggest_autogen/mocs_compilation.s: algolia-suggest_autogen/mocs_compilation.cpp.s

.PHONY : algolia-suggest_autogen/mocs_compilation.s

# target to generate assembly for a file
algolia-suggest_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/algolia-suggest_autogen/mocs_compilation.cpp.s
.PHONY : algolia-suggest_autogen/mocs_compilation.cpp.s

lib/algoliaindex.o: lib/algoliaindex.cpp.o

.PHONY : lib/algoliaindex.o

# target to build an object file
lib/algoliaindex.cpp.o:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliaindex.cpp.o
.PHONY : lib/algoliaindex.cpp.o

lib/algoliaindex.i: lib/algoliaindex.cpp.i

.PHONY : lib/algoliaindex.i

# target to preprocess a source file
lib/algoliaindex.cpp.i:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliaindex.cpp.i
.PHONY : lib/algoliaindex.cpp.i

lib/algoliaindex.s: lib/algoliaindex.cpp.s

.PHONY : lib/algoliaindex.s

# target to generate assembly for a file
lib/algoliaindex.cpp.s:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliaindex.cpp.s
.PHONY : lib/algoliaindex.cpp.s

lib/algoliasearch.o: lib/algoliasearch.cpp.o

.PHONY : lib/algoliasearch.o

# target to build an object file
lib/algoliasearch.cpp.o:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasearch.cpp.o
.PHONY : lib/algoliasearch.cpp.o

lib/algoliasearch.i: lib/algoliasearch.cpp.i

.PHONY : lib/algoliasearch.i

# target to preprocess a source file
lib/algoliasearch.cpp.i:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasearch.cpp.i
.PHONY : lib/algoliasearch.cpp.i

lib/algoliasearch.s: lib/algoliasearch.cpp.s

.PHONY : lib/algoliasearch.s

# target to generate assembly for a file
lib/algoliasearch.cpp.s:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasearch.cpp.s
.PHONY : lib/algoliasearch.cpp.s

lib/algoliasuggest.o: lib/algoliasuggest.cpp.o

.PHONY : lib/algoliasuggest.o

# target to build an object file
lib/algoliasuggest.cpp.o:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasuggest.cpp.o
.PHONY : lib/algoliasuggest.cpp.o

lib/algoliasuggest.i: lib/algoliasuggest.cpp.i

.PHONY : lib/algoliasuggest.i

# target to preprocess a source file
lib/algoliasuggest.cpp.i:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasuggest.cpp.i
.PHONY : lib/algoliasuggest.cpp.i

lib/algoliasuggest.s: lib/algoliasuggest.cpp.s

.PHONY : lib/algoliasuggest.s

# target to generate assembly for a file
lib/algoliasuggest.cpp.s:
	$(MAKE) -f CMakeFiles/SearchStaticLib.dir/build.make CMakeFiles/SearchStaticLib.dir/lib/algoliasuggest.cpp.s
.PHONY : lib/algoliasuggest.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/algolia-suggest.dir/build.make CMakeFiles/algolia-suggest.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... algolia-suggest"
	@echo "... SearchStaticLib"
	@echo "... algolia-suggest_autogen"
	@echo "... SearchStaticLib_autogen"
	@echo "... SearchStaticLib_autogen/mocs_compilation.o"
	@echo "... SearchStaticLib_autogen/mocs_compilation.i"
	@echo "... SearchStaticLib_autogen/mocs_compilation.s"
	@echo "... algolia-suggest_autogen/mocs_compilation.o"
	@echo "... algolia-suggest_autogen/mocs_compilation.i"
	@echo "... algolia-suggest_autogen/mocs_compilation.s"
	@echo "... lib/algoliaindex.o"
	@echo "... lib/algoliaindex.i"
	@echo "... lib/algoliaindex.s"
	@echo "... lib/algoliasearch.o"
	@echo "... lib/algoliasearch.i"
	@echo "... lib/algoliasearch.s"
	@echo "... lib/algoliasuggest.o"
	@echo "... lib/algoliasuggest.i"
	@echo "... lib/algoliasuggest.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

